spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/security_project_2
    username: postgres
    password: version
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    open-in-view: false